preferred_syntax = :sass
http_path = '/'
css_dir = 'stylesheets'
sass_dir = 'stylesheets/sass'
#images_dir = 'assets/images'
#javascripts_dir = 'assets/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed